test

diff --git a/.github/workflows/docsbot-command.yml b/.github/workflows/docsbot-command.yml
--- a/.github/workflows/docsbot-command.yml
+++ b/.github/workflows/docsbot-command.yml
@@ -27,10 +27,18 @@ jobs:
           PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
         run: echo "$PAYLOAD_CONTEXT"
 
+      - name: Create URL to the run output
+        id: vars
+        run: echo "run-url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_OUTPUT
+
       - name: Validate command
         id: validate
         run: |
-          [[ -z "${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}" ]] && { echo "error-message=You didn't provide a command" >> $GITHUB_OUTPUT; exit 1; }
+          cmd="${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}";
+          [[ -z "${cmd}" ]] && { echo "error-message=You didn't provide a command" >> $GITHUB_OUTPUT; exit 1; };
+          
+          array=("ping" "stage");
+          [[ ! " ${array[*]} " =~ " ${cmd} " ]] && { echo "I don't know what the command \"${cmd}\" means" >> $GITHUB_OUTPUT; exit 1;};
 
       - name: Process command
         id: process
@@ -39,25 +47,6 @@ jobs:
         with:
           event-type: ${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}
           client-payload: ${{ github.event.client_payload }}
-
-#      - name: Create URL to the run output
-#        id: vars
-#        run: echo "run-url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_OUTPUT
-#
-#      - name: Add reaction
-#        uses: peter-evans/create-or-update-comment@v2
-#        if: not steps.process.outputs.error-message
-#        with:
-#          token: ${{ secrets.DOCSBOT_ACTION_TOKEN }}
-#          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
-#          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
-#          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
-#          body: |
-#            Hello @${{ github.event.client_payload.github.actor }}!
-#
-#            [Click here to see the command run output][1]
-#
-#            [1]: ${{ steps.vars.outputs.run-url }}
 
       - name: Add hooray reaction
         uses: peter-evans/create-or-update-comment@v2
@@ -68,6 +57,10 @@ jobs:
           issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
           comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
           reaction-type: hooray
+          body: |
+            [1]: ${{ steps.vars.outputs.run-url }}
+            
+            [Here's the action detail][1]
 
       - name: Add confused reaction
         uses: peter-evans/create-or-update-comment@v2
@@ -79,5 +72,8 @@ jobs:
           comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
           reaction-type: confused
           body: |
+            [1]: ${{ steps.vars.outputs.run-url }}
             > ${{ steps.validate.outputs.error-message }}
             > ${{ steps.process.outputs.error-message }}
+            
+            [Here's the action detail][1]
