Test

diff --git a/.github/workflows/docsbot-command.yml b/.github/workflows/docsbot-command.yml
--- a/.github/workflows/docsbot-command.yml
+++ b/.github/workflows/docsbot-command.yml
@@ -27,26 +27,41 @@ jobs:
           PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
         run: echo "$PAYLOAD_CONTEXT"
 
-      - name: Create URL to the run output
-        id: vars
-        run: echo "run-url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_OUTPUT
+      - name: Validate command
+        id: validate
+        run: |
+          [[ -z "${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}" ]] && { echo "error-message=You didn't provide a command" >> $GITHUB_OUTPUT; }
 
-      - name: Add reaction
-        uses: peter-evans/create-or-update-comment@v2
+      - name: Process command
+        id: process
+        if: not steps.validate.outputs.error-message
+        uses: peter-evans/repository-dispatch@v2
         with:
-          token: ${{ secrets.DOCSBOT_ACTION_TOKEN }}
-          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
-          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
-          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
-          body: |
-            Hello @${{ github.event.client_payload.github.actor }}!
-            
-            [Click here to see the command run output][1]
-            
-            [1]: ${{ steps.vars.outputs.run-url }}
+          event-type: ${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}
+          client-payload: ${{ github.event.client_payload }}
+
+#      - name: Create URL to the run output
+#        id: vars
+#        run: echo "run-url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_OUTPUT
+#
+#      - name: Add reaction
+#        uses: peter-evans/create-or-update-comment@v2
+#        if: not steps.process.outputs.error-message
+#        with:
+#          token: ${{ secrets.DOCSBOT_ACTION_TOKEN }}
+#          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
+#          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
+#          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
+#          body: |
+#            Hello @${{ github.event.client_payload.github.actor }}!
+#
+#            [Click here to see the command run output][1]
+#
+#            [1]: ${{ steps.vars.outputs.run-url }}
 
       - name: Add hooray reaction
         uses: peter-evans/create-or-update-comment@v2
+        if: (not steps.process.outputs.error-message) && (not steps.validate.outputs.error-message)
         with:
           token: ${{ secrets.DOCSBOT_ACTION_TOKEN }}
           repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
@@ -56,9 +71,13 @@ jobs:
 
       - name: Add confused reaction
         uses: peter-evans/create-or-update-comment@v2
+        if: (steps.process.outputs.error-message) || (steps.validate.outputs.error-message)
         with:
           token: ${{ secrets.DOCSBOT_ACTION_TOKEN }}
           repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
           issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
           comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
           reaction-type: confused
+          body: |
+            > ${{ steps.validate.outputs.error-message }}
+            > ${{ steps.process.outputs.error-message }}
